### PR TITLE
Add tox & travis cfg + various fixes

### PR DESCRIPTION
**Pull request by davidfischer-ch**
Hello,

I am interested in using your project for my own.
It looks simple, clean and not too heavy for providing the soft deletion feature!

However I am using Python 3.4 & Django 1.7 and the 2/14 tests related to restore fails.

### CODE REVIEW

**Comment by meteozond** [comment]
Dear, @davidfischer-ch, thank you so match for your contribution. I'm so sorry, I've shamefully missed your PR at all and already implemented CI (bc83740) myself, but I'm cherry-peaking some of you commits now:
- 79c1410 Find packages recursively
- 0928399 Update Git ignore list
- 8db3347 Make setup.py executable.
- ac5de57 Replace commit_on_success_unless_managed by atomic

But one of the commits (099b280) confusing me a bit, it got a mix of non atomic changes, which should be discussed separately:
- I've noticed recently that tests could be started from `setup.py`, so it's a part of the package now, and [excluding tests from dist](https://github.com/davidfischer-ch/django-permanent/blob/099b28066962994082063668fcda8f46da665fbe/setup.py#L14) isn't necessary any more.
- From the beginning I decided to keep `test_app` into the folder. Yes it became the problem for Django 1.7, what could be eliminated adding test app to the test settings (should be done from the beginning).
- I didn't used `tox` earlier, but, if I'm not mistaken, it doesn't provide variability of dependencies minor versions, so I'm going to stay with the manual environment handling, correct me if I was wrong.
- Future imports, style fixes and coverage reports undoubtedly are very important but I can't merge them separately from some unwanted changes. I'm going implement them by myself later (#16, #17, #18), if you don't mind. Or you can make separate PRs, if you wish.
  Sorry, again for my half year silence, and thank you so match again for your participation.

**Comment by davidfischer-ch** [comment]
Hello,

Thanks for looking at my contributions.

In fact, tox is a powerful tool to create multiple virtualenv locally in order to test an application against multiple versions of the dependencies.

Unfortunately my commit is not "atomic".
However is it possible to merge it and then revert some of the code yourself?

Also [here](https://github.com/jezdez/django-appconf/blob/develop/tox.ini) is a cleaner, more recent example of tox.ini file.

Regards,

David

**Comment by davidfischer-ch** [comment]
You can see tox as a local Travis CI.

**Comment by meteozond** [comment]
ok, I've got it, thanks.

**Pull request closed without merging**
