### PR TITLE
Django 3.0 Support

### PR DESCRIPTION
**Pull request by mwfister**
Python 2 support was dropped in Django 2.0, with Django 3.0 removing private python 2 compatibility APIs like `six`.

- [x] Added Django 3.0 support
- [x] Python 2 compatibility removed
- [x] With no python version overlap, removed django 1.6 as a supported version

As an aside, with the departure of the original author, do you intend to continue supporting this package? We find this package quite useful and have devs willing to assist if you're happy providing write access.

### CODE REVIEW

**Comment by jarekwg** [comment]
@meteozond do you know who we could contact to get write access for this repo (in the absence of someone from @MnogoByte continuing its maintenance). Would be happy to accept a transfer of the project too, if that's on the table.

**Comment by carlkibler** [comment]
Perhaps just fork it and release as django-permanent2, and post on open PRs here about the change? (if you haven't already)

**Comment by jarekwg** [comment]
That's a bit of a hostile takeover approach. I'll try a little harder to get a hold of the current maintainers.

@atin65536 are you the current maintainer? Please let me know your current status with this repo. Happy to discuss over private message. We rely on this library quite heavily in production and would be happy to take it under our wing if that's what's required to keep it alive.

**Comment by aidanlister** [comment]
@jarekwg might need to swap over to https://github.com/makinacorpus/django-safedelete

Seems like the best option per https://djangopackages.org/grids/g/deletion/

**Comment by jarekwg** [comment]
Hey @meteozond / @atin65536,

Just asking again if either of you would be able to help getting this repository transferred. We (https://github.com/uptick), are still using django-permanent heavily in production, and have just put together support for Python311/Django4/Mypy: https://github.com/uptick/django-permanent/pull/1

If you can't get us a contact at MnogoByte to perform the transfer, could we at least get pypi publish perms, so that we can start publishing new versions from our fork?

Thanks in advance!

**Comment by meteozond** [comment]
Hello @jarekwg! It's been a couple of years since both @atin65536 and I left @mnogobyte. I've been eager to further develop **django-permanent**, but unfortunately, my request to transfer the repository was declined by @Mnogobyte's management. As a result, the project is currently in a state of limbo, caught between threir desire to save full control and lack of resources to support it.

Despite this setback, I've continued to use this package in my subsequent projects. At this point, I'm considering making a second attempt to contact management. However, if that doesn't work, I'm thinking of forking and renaming in order to continue its development.

**Comment by jarekwg** [comment]
Hey @meteozond,
Thanks for getting back to me!
That sounds perfect! Thanks for the reply! Please let us know how it goes, and if you do fork and continue elsewhere, please see if we could use https://github.com/uptick/django-permanent/pull/1 as a starting point. We've had to pull out a lot of hair to find a way to get this magic to work with both typing _and_ django4. Feel free to comment on that PR for additional clarification around any decisions made.

**Pull request closed without merging**
