### PR TITLE
need check if self.field.remote_field.model has `all_objects` attribute

### PR DESCRIPTION
**Pull request by quocduan**
need check if self.field.remote_field.model has `all_objects` attribute

### CODE REVIEW

**Review by meteozond — CHANGES_REQUESTED** [review]
Really don't understand the case when it could happen, because there is a check for PermanentModel. What a about to add tests for this situation?

**Comment by kregoslup** [comment]
Suppose we have two models, User and Country, user is permanent.

```
class User(PermanentModel):
    country = models.ForeignKey(Country)

class Country(model.Model)
    name = models.Model

```
Now when you soft delete user and then try to get country from that user it throws AttributeError:

u = User.deleted_objects.first()
u.country

I can provide tests if you want. I think this issue occures only in Django > 1.9

**Comment by meteozond** [comment]
Hm, looks reasonable - won't you mind to add test for this case.

**Comment by helgihg** [comment]
This patch would be appreciated into the main branch. Adding it to my code fixes a problem that I have when deleting an object based on PermanentModel which is a foreign key to a model which is only based on models.Model, but has a custom manager made from a custom query set. (objects = OtherQuerySet.as_manager()). - Django 1.11.0

**Comment by kregoslup** [comment]
@helgihg It's already on master branch - https://github.com/meteozond/django-permanent/commit/08a619595c76be83f3a07b901987f52a2d0cc66a

**Comment by helgihg** [comment]
@kregoslup Cool, thanks! I'll wait for 1.1.6 so that I can update with pip, but that's great to know. :)

**Comment by meteozond** [comment]
covered by #65

**Pull request closed without merging**
