### PR TITLE
Upgrade/django19

### LINKED ISSUE #35: import_by_path() has been deprecated.
I am getting this warning in Django 1.8:

```
django_permanent/models.py:39: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  field = import_by_path(settings.FIELD_CLASS)
```

### PR DESCRIPTION
**Pull request by jarekwg**
Yo, 

Made this pull request a while back and it got outdated. It fixes #35, #36

Just rebased it now and updated travis.yml.

I see there's some other pull requests (#40, #41) trying to do the same thing..
Pretty sure this already covers everything, but if not, maybe we can consolidate our approaches?

### CODE REVIEW

**Comment by cancan101** [comment]
bump?

**Comment by andybak** [comment]
Hmmmm. Is this project still breathing? @meteozond - would you prefer it was transferred to someone else?

**Comment by meteozond** [comment]
Wow! Hi, 1.9 is my first priority in this lib, but I got busy at the moment. I'll check this PR soon.

**Comment by ydaniv** [comment]
Getting this warning:

```
.../site-packages/django_permanent/related.py:21: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
  field = self.model._meta.get_field_by_name(settings.FIELD)[0]
```

Perhaps it's possible to clean it together with this PR?

**Comment by jarekwg** [comment]
Sure, will take a look.

**Comment by jarekwg** [comment]
Deprecation warnings should all be gone now.

**Comment by ydaniv** [comment]
:+1:

**Comment by pawelnowak** [comment]
Looking forward to see this one merged

**Comment by aidanlister** [comment]
@meteozond can we get this merged and a new stable release?

**Comment by meteozond** [comment]
Thanks to all, Merged @atin65536 version with preserved Django 1.6 and some additional fixes.

**Pull request merged**
